require 'pathname'
require 'json'

task :build do
  data = {}

  Dir['../assets/*.svg'].each do |path|
    svg = Pathname(path).read
    key = File.basename(path, '.svg')

    data[key] = svg
      .gsub(/<svg.+>/, '')
      .gsub(/<\/svg>/, '')
      .gsub(/stroke="#\d+"\s?/, '')
      .gsub(/stroke="black"\s?/, '')
      .gsub(/stroke-width="2"\s?/, '')
      .gsub(/stroke-linecap="round"\s?/, '')
      .gsub(/stroke-linejoin="round"\s?/, '')
      .gsub(/\n/, '')
      .strip
  end

  File.open('lib/assets/data.json', 'w') do |f|
    f.write(JSON.pretty_generate(data))
  end
end
